export const DiscActionTypes = Object.freeze({
    FETCH_RESOURCES_STARTED: "FETCH_RESOURCES_STARTED",
    FETCH_RESOURCES_SUCCESSED: "FETCH_RESOURCES_SUCCESSED",
    FETCH_RESOURCES_FAILED: "FETCH_RESOURCES_FAILED",

    FETCH_RESOURCES_MORE_STARTED: "FETCH_RESOURCES_MORE_STARTED",
    FETCH_RESOURCES_MORE_SUCCESSED: "FETCH_RESOURCES_MORE_SUCCESSED",
    FETCH_RESOURCES_MORE_FAILED: "FETCH_RESOURCES_MORE_FAILED_FAILED"
})
